name: Build Cryptography on Power

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy: 
      matrix:
        architecture: [ppc64le]
        platform: [linux]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - uses: uraimo/run-on-arch-action@v2
        name: Install dependencies and build cryptography
        with:
          arch: ppc64le
          distro: ubuntu20.04
      
          run: |
            arch
            apt-get update -y
            apt-get install -y git python3 build-essential openssl libssl-dev enchant python3-venv python3-pip rustc 
            pip3 install --upgrade pip; 
            pip3 install setuptools-rust; 
            pip3 install wheel; 
            pip3 install check-wheel-contents;

            #Building cryptography
            chmod +x ./build.sh
            ./build.sh
